#!/usr/bin/env bash

# Plug this into openvpn.conf as the client-connect script
# and dynamically add iptables rules
#
# Author Ruoyan Wong
# Date   10/01/2011

function delRules {

    while true;do
        eval "$1"
        [ $? != 0 ] && break
    done

}

IPTABLES="sudo /sbin/iptables"
LOGFILE="/var/log/openvpn-iptables.log"

USERNAME=${common_name}
DATE=`date +"%Y/%m/%d %H:%M"`
TITLE="[${DATE}][${USERNAME}][DEL]"
CLIENT_ADDR=${ifconfig_pool_remote_ip}

echo "USER $USERNAME LOGOUT." >> $LOGFILE
echo "${TITLE} ${IPTABLES} -D FORWARD -s $CLIENT_ADDR -j $USERNAME" >> $LOGFILE
delRules "${IPTABLES} -D FORWARD -s $CLIENT_ADDR -j $USERNAME >> /dev/null 2>&1"
echo "${TITLE} ${IPTABLES} -F ${USERNAME}" >> $LOGFILE
${IPTABLES} -F ${USERNAME} >> /dev/null 2>&1 
echo "${TITLE} ${IPTABLES} -X ${USERNAME}" >> $LOGFILE
delRules "${IPTABLES} -X ${USERNAME} >> /dev/null 2>&1" 

exit 0 
